# Generated by Django 5.2.5 on 2025-08-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_wallet_wise', '0002_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ahorro', 'Ahorro'), ('inversion', 'Inversión')], max_length=10),
        ),
    ]
